[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
